### ISSUE TITLE
expired cert

### ISSUE THREAD

**Issue by justgrimes** [cmgiven/justgrimes#14]
justgrimes.review cert needs to be renewed; it appears to have expired. 

_justgrimes.review uses an invalid security certificate. The certificate expired on November 8, 2017, 11:15 AM. The current time is November 9, 2017, 12:00 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE_

**Comment by cmgiven** [comment]
Fixed. And because nothing's worth doing if you can't overdo it:

* Slack integration to the Code for DC slack to alert us if there are renewal problems.
* Tighter cipher suites to secure an A+ from SSL Labs (up from an A).
* Switched to Linode DNS (yet to propogate, hopefully I didn't screw it up) in order to set a [CAA](https://tools.ietf.org/html/rfc6844) record.
